avoid sed -r

diff --git a/test/future-created/EXEC b/test/future-created/EXEC
--- a/test/future-created/EXEC
+++ b/test/future-created/EXEC
@@ -13,18 +13,17 @@ rm -f ?
 exitcode="$?"
 
 if [ "$exitcode" != 0 ] ; then
-    echo >&2 "*** Exit code not zero"
-    exit 1
+	echo >&2 "*** Exit code not zero"
+	exit 1
 fi
 
 if ! cmp list.err stderr ; then
-#if ! fgrep "Warning: 'B' has modification time in the future" list.err ; then
-    echo >&2 "*** Missing warning about future timestamp of 'B'"
-    echo >&2 list.err:
-    echo >&2 __________
-    cat >&2 list.err
-    echo >&2 __________
-    exit 1
+	echo >&2 "*** Missing warning about future timestamp of 'B'"
+	echo >&2 list.err:
+	echo >&2 __________
+	cat >&2 list.err
+	echo >&2 __________
+	exit 1
 fi
 
 # Execute again:  The warning must still be output.
@@ -35,14 +34,13 @@ sleep 2
 exitcode="$?"
 
 if [ "$exitcode" != 0 ] ; then
-    echo >&2 "*** Exit code not zero"
-    exit 1
+	echo >&2 "*** Exit code not zero"
+	exit 1
 fi
 
 if ! cmp list.err stderr ; then
-#if ! fgrep "Warning: 'B' has modification time in the future" list.err ; then
-    echo >&2 "*** Missing warning about future timestamp of 'B'"
-    exit 1
+	echo >&2 "*** Missing warning about future timestamp of 'B'"
+	exit 1
 fi
 
 rm -f ?
