use exit code 4 consistently for unrecoverable errors

diff --git a/test/option-f-empty/EXEC b/test/option-f-empty/EXEC
--- a/test/option-f-empty/EXEC
+++ b/test/option-f-empty/EXEC
@@ -3,14 +3,14 @@
 ../../stu -f '' 2>list.err
 exitcode="$?"
 
-if [ "$exitcode" != 2 ]; then
-    echo >&2 "*** Wrong exit code"
-    exit 1
+if [ "$exitcode" != 4 ]; then
+	echo >&2 "*** Wrong exit code"
+	exit 1
 fi
 
-if ! fgrep -q "./stu: *** Option -f must take non-empty argument" list.err ; then
-    echo >&2 "*** Missing error message"
-    exit 1
+if ! grep -Fq "./stu: *** Option -f must take non-empty argument" list.err ; then
+	echo >&2 "*** Missing error message"
+	exit 1
 fi
 
 exit 0
diff --git a/test/status-fail/EXEC b/test/status-fail/EXEC
--- a/test/status-fail/EXEC
+++ b/test/status-fail/EXEC
@@ -5,13 +5,13 @@ export STU_STATUS=1
 ../../stu 2>list.err >list.out
 exitcode="$?"
 
-[ "$exitcode" = 2 ] || {
-	echo >&2 '*** Wrong exit code'
+[ "$exitcode" = 4 ] || {
+	echo >&2 '*** Exit code'
 	exit 1
 }
 
 grep -qF '../../stu: *** Refusing to run recursive Stu; unset $STU_STATUS to circumvent' list.err || {
-	echo >&2 '*** Missing error message'
+	echo >&2 '*** Error message'
 	exit 1
 }
 
