fixes for FreeBSD

diff --git a/sh/mktest b/sh/mktest
--- a/sh/mktest
+++ b/sh/mktest
@@ -143,7 +143,7 @@ do
 	fi
 
 	# There are no files in the test directory (ignoring dotfiles) 
-	if [ "$(ls -1 "$file" | wc -l)" = 0 ] ; then
+	if [ "$(echo $(ls -1 "$file" | wc -l))" = 0 ] ; then
 		if [ "$emptyok" != 1 ] ; then
 			echo >&2 "$0: *** Test directory $file/ does not contain any files"
 			error=1
@@ -153,7 +153,7 @@ do
 		continue;
 	fi
 
-	echo __________________________________
+	echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
 	echo cd "$file"
 	cd "$file"
 
@@ -248,8 +248,12 @@ do
 					if fgrep -q -- "$(cat INCONTENT)" "$target" ; then
 						echo "INCONTENT...correct"
 					else
-						echo >&2 "$0: *** '$(cat INCONTENT)' was not found in generated file"
-						error=1
+					    echo >&2 "$0: *** '$(cat INCONTENT)' must appear in generated file"
+					    echo >&2 "$target:"
+					    echo >&2 ____
+					    cat "$target"
+					    echo >&2 ____
+					    error=1
 					fi
 				fi
 				
@@ -302,7 +306,7 @@ do
 
 		# Check that at least one line of error message is generated 
 		if [ "$exitcode_correct" != 0 -a \! -r STDERR ]; then
-			if [ \! \( "$(cat list.def.err | wc -l)" -gt 0 \) ]; then
+			if [ \! \( "$(echo $(cat list.def.err | wc -l))" -gt 0 \) ]; then
 				echo >&2 "$0: *** Nothing written to stderr although exit code is >0"
 				error=1
 			fi
@@ -455,7 +459,7 @@ do
 	fi
 done
 
-echo __________________________________
+echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
 
 time_end="$(date +%s)"
 time_diff="$(expr $time_end - $time_begin)"
@@ -463,7 +467,7 @@ printf 'Runtime: %u:%02u\n' "$(expr $time_diff / 60)" "$(expr $time_diff % 60)"
 
 if [ "$errors" != 0 ]
 then
-	echo >&2 "$0: *** The following $(<../error.log wc -l) tests failed:"
+	echo >&2 "$0: *** The following $(echo $(<../error.log wc -l)) tests failed:"
 	cat ../error.log
 	exit 1
 else
diff --git a/test/sigusr1-immediately/EXEC b/test/sigusr1-immediately/EXEC
--- a/test/sigusr1-immediately/EXEC
+++ b/test/sigusr1-immediately/EXEC
@@ -6,7 +6,7 @@ echo '../../stu.test -j1000 &'
 ../../stu.test -j1000 >list.out 2>list.err &
 pid="$!"
 
-# Write until a first line has been written
+# Wait until a first line has been written
 while [ \! -s list.out ] ; do : ; done 
 
 echo "kill -s USR1 $pid"
@@ -15,10 +15,22 @@ kill -s USR1 "$pid" || {
 	exit 1
 }
 
-sleep 1
+echo sleep 1
+sleep 1 || exit 1
+echo done sleeping
 
-if [ $(ps -fe | grep 74634275 | grep -v grep | wc -l) = 0 ]; then
-	echo >&2 "$0: *** Stu is still running"
+count="$(echo $(ps -fA | grep 7463194 | grep -v grep | wc -l))"
+echo "count=$count"
+if [ "$count"  = 0 ]; then
+	echo >&2 "$0: *** Stu must still be running"
+	echo >&2 stdout:
+	echo >&2 ____
+	cat >&2 list.out
+	echo >&2 ___
+	echo >&2 stderr:
+	echo >&2 ____
+	cat >&2 list.err
+	echo >&2 ___
 	exit 1
 fi
 
@@ -27,11 +39,14 @@ grep -qE '^STATISTICS  ' list.out || {
 	exit 1
 }
 
-kill -INT "$pid"
+kill -INT "$pid" || {
+    echo >&2 "*** Error killing PID '$pid'"
+    exit 1
+}
 
-sleep 1
+sleep 1 || exit 1
 
-if [ $(ps -fe | grep 74634275 | grep -v grep | wc -l) \!= 0 ]; then
+if [ "$(echo $(ps -fA | grep 7463194 | grep -v grep | wc -l))" \!= 0 ]; then
 	echo >&2 "$0: *** Stu is still running"
 	exit 1
 fi
