cycles

diff --git a/sh/mktest b/sh/mktest
--- a/sh/mktest
+++ b/sh/mktest
@@ -2,8 +2,8 @@
 #
 # Perform all unit tests.  Each unit test is in one subdirectory of the
 # directory test/.  By default, each test directory contains a file
-# 'main.stu' that performs one unit test.  Additional files may be 
-# present to configure how the test is performed, see below.  
+# 'main.stu' that performs one unit test.  Additional files may be
+# present to configure how the test is performed; see below.
 # 
 # INVOCATION
 #
@@ -12,10 +12,10 @@
 # Without any arguments, perform all tests.  With one or more arguments,
 # perform the given tests.  The given test names are the names of the
 # subdirectories of test/, and may or may not include the 'test/'
-# prefix.  The arguments may contain glob patterns. 
+# prefix.  The arguments may contain glob patterns.  (No test names
+# contain the glob characters *, ?, etc.) 
 #
 # PARAMETERS
-#
 #     $emptyok	Set to non-empty to *not* output an error for empty test
 #               directories; useful after doing "rm" in a version
 #		control system on one, since that leaves a directory
@@ -25,10 +25,16 @@
 #     $VARIANT  Other variant of the compiled file; the default is to
 #		take the file that matches the value of $NDEBUG
 #     $verbose  Set to non-empty for verbose output 
+#     $notall	If non-empty, exit on the first error, instead of
+#		running everything  
 #
 # OUTPUT FILES
-# 
 #     error.log		List of tests that failed
+#
+# EXIT STATUS 
+#	0	All tests succeeded
+#	1	At least one test failed
+#	2	Internal error 
 #
 # TEST SPECIFICATION 
 #
@@ -45,10 +51,25 @@
 # * There may be other files present used by the test; these are part of
 #   the Stu release, i.e., they are under version control. 
 #
+# The names of unit tests, i.e., the name of the directories under test/
+# follow a pattern:
+#
+# * test/VERSION-ID
+#	These are tests for features introduced in Stu version VERSION.
+#	This was introduced in Stu 2.5, and therefore the assignment of
+#	VERSION numbers for older versions is approximate.  The goal is
+#	to be able to run all tests in asciibetical order so as to test
+#	older features first.  Presumably, these are the features that
+#	should be fixed first when working on Stu.
+# * test/NAME-ID
+#	These are tests for the feature named NAME, with ID being an
+#	integer.  Ideally, these would be migrated to the VERSION-ID
+# 	scheme.  
+#
 # SPECIFICATION FILES
 #
 # Each of these files can be placed in the individual test directory to
-# enable additional checks or behaviours.  All of these files are optional. 
+# enable additional checks or behaviors.  All of these files are optional. 
 #
 # TARGET       The name of the target that is built in the test, instead
 #              of the default 'A'.  This does not change the invocation:
@@ -71,15 +92,15 @@
 # NOCOLOR      Don't test for color in stderr (e.g., with the -y option)
 # CONTENT      Prescribe the exact content of the built file
 # INCONTENT    Prescribe strings that must appear in the built file 
-# STDOUT       The exact output of the command
-# STDERR       The exact content of the error output
-# INSTDOUT     Prescribe strings that must appear on stdout 
-# INSTDERR     Prescribe strings that must appear in the error message
-# NOTINSTDERR  A text that must not be present in the error output
+# STDOUT       The exact output of Stu
+# STDERR       The exact error output of Stu
+# INSTDOUT     Prescribe strings that must appear in Stu's output
+# INSTDERR     Prescribe strings that must appear in Stu's error output
+# NOTINSTDERR  A text that must not be present in Stu's error output
 # TTYSTDOUTERR The output and error output (interleaved) when in TTY mode
 # EXEC         Can be an alternative test script; it can do anything and
 #              should return a sensible exit code (i.e., 0 on success,
-#              nonzero otherwise).  It should also behave like ./mktest,
+#              nonzero otherwise).  It should also behave like sh/mktest,
 #              e.g., output '***' only on error, etc.
 #
 # For the files beginning with 'IN', each line contains a string that
@@ -92,7 +113,7 @@
 #   Usually, these scripts use "sleep 2", i.e., sleep for two seconds to
 #   make sure that there is a difference in timestamps of at least one
 #   second on systems where file modification times have a precision of
-#   only one second. 
+#   only one second.  An alternative is to use sh/touch_old. 
 # * Tests output '***' only in case of error.  This is convenient for
 #   grepping while the tests are running.
 # * Tests use 'diff' to compare files, not 'cmp'. 
@@ -112,6 +133,14 @@
 
 # Set to "1" on error 
 errors=0
+
+error_do() {
+	errors=1
+	[ -n "$notall" ] && { 
+		echo >&2 "[31m$0: *** failed[m"
+		exit 1 
+	}
+}
 
 time_begin="$(date +%s)"
 
@@ -158,7 +187,7 @@ do
 		echo >&2 "$0: *** '$file' is not a directory"
 		error=1
 		echo "$file" >&6
-		errors=1
+		error_do
 		continue
 	fi
 
@@ -168,7 +197,7 @@ do
 			echo >&2 "$0: *** Test directory $file/ does not contain any files"
 			error=1
 			echo "$file" >&6
-			errors=1
+			error_do
 		fi
 		continue;
 	fi
@@ -177,7 +206,7 @@ do
 	echo cd "$file"
 	cd "$file"
 
-	../../sh/delete_tmps || exit 1
+	../../sh/delete_tmps || exit 2
 
 	# Check that all all-uppercase files are of one of the allowed files 
 	allowed=",EXITSTATUS,PARALLEL,INSTDOUT,INSTDERR,NOTINSTDERR,STDERR,TTYSTDOUTERR,CMD,CMDPREFIX,TARGET,INCONTENT,CONTENT,EXEC,STDOUT,NOSECOND,NOTTY,NOCOLOR,"
@@ -469,7 +498,7 @@ do
 		if [ -r PARALLEL ]; then
 			ks="$(sed -e '/^[[:space:]]*$/d' <PARALLEL)"
 			for k in $ks; do
-				../../sh/delete_tmps || exit 1
+				../../sh/delete_tmps || exit 2
 				echo $CMDPREFIX ../../stu.test "$CMD" -j "$k"
 				eval $CMDPREFIX ../../stu.test $CMD -j $k \>list.def.out 2\>list.def.err
 				if [ $? != 0 ]
@@ -483,12 +512,12 @@ do
 		fi	
 	fi	
 
-	../../sh/delete_tmps || exit 1
+	../../sh/delete_tmps || exit 2
 	cd ..
 
 	if [ "$error" != 0 ] ; then
 		echo "$file" >&6
-		errors=1
+		error_do
 	fi
 done
 
