testing:  non-verbose output by default

diff --git a/sh/mktest b/sh/mktest
--- a/sh/mktest
+++ b/sh/mktest
@@ -23,7 +23,7 @@
 #		the debug version is tested 
 #     $VARIANT  Other variant of the compiled file; the default is to
 #		take the file that matches the value of $NDEBUG
-#     $verbose  Set to non-empty for verbose output 
+#     $verbose  Set to {0,1,2} for verbose levels; default is 0
 #     $notall	If non-empty, exit on the first error, instead of
 #		running everything  
 #     $emptyok	Set to non-empty to *not* output an error for empty test
@@ -136,13 +136,35 @@
 # shell scripts), because otherwise we can't use $? to check the exit
 # code of Stu.  
 
-# Set to "1" on error 
-errors=0
+output_next()
+{
+	echo >&7 '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
+	echo >&7 cd "$file"
+	if [ "$verbose" = 0 ] ; then
+		printf '[2K%s' "$file"
+	fi
+}
+
+output_end()
+{
+	echo >&7 '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
+	if [ "$verbose" = 0 ] ; then
+		printf '[2K'
+	fi
+}
+
+ret=0
+time_begin=$(sh/now)
 
 mkdir -p log
 exec 6>log/error.log
 
-time_begin=$(sh/now)
+verbose=${verbose:-0}
+printf '%s\n' "$verbose" | grep -q -E '^[012]$' || {
+	echo >&2 "$0: *** Invalid verbosity level '$verbose'"
+	exit 2
+}
+[ "$verbose" -ge 1 ] && exec 7>&1 || exec 7>/dev/null
 
 rm -f bin/stu.test || exit 2
 if [ "$VARIANT" ] ; then
@@ -184,7 +206,7 @@ do
 
 	if [ ! -d "$file" ]; then
 		echo >&2 "$0: *** '$file' is not a directory"
-		errors=1
+		ret=1
 		echo "$file" >&6
 		continue
 	fi
@@ -193,14 +215,13 @@ do
 	if [ "$(echo $(ls -1 "$file" | wc -l))" = 0 ] ; then
 		if [ "$emptyok" != 1 ] ; then
 			echo >&2 "$0: *** Test directory $file/ does not contain any files"
-			errors=1
+			ret=1
 			echo "$file" >&6
-			continue;
+			continue
 		fi
 	fi
 
-	echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
-	echo cd "$file"
+	output_next
 	cd "$file"
 
 	../../sh/rm_tmps || exit 2
@@ -226,31 +247,29 @@ do
 	# The following will save:  list.def.out and list.def.err 
 
 	if [ -r EXEC ]; then
-
 		if [ -r EXITSTATUS -o -r PARALLEL -o -r INSTDOUT -o -r INSTDERR \
 			-o -r STDERR -o -r NOTINSTDERR -o -r CMD -o -r CMDPREFIX \
 			-o -r TARGET -o -r INCONTENT -o -r CONTENT \
 			-o -r STDOUT -o -r NOSECOND -o -r NOTTY -o -r TTYSTDOUTERR -o -r NOCOLOR ]; then
 			echo >&2 "$0: *** EXEC does not allow any other file"
-			errors=1
+			ret=1
 			echo "$file" >&6
 			continue
 		fi
 
-		echo >&2 ./EXEC
-		./EXEC
+		echo >&7 ./EXEC
+		./EXEC 1>&7
 		if [ "$?" != 0 ]; then
 			echo >&2 "$0: *** EXEC failed"
 			error=1
 		fi
-
 	else
 		# Execute command
-		echo $CMDPREFIX ../../bin/stu.test "$CMD"
+		echo >&7 $CMDPREFIX ../../bin/stu.test "$CMD"
 		eval $CMDPREFIX ../../bin/stu.test $CMD \>list.def.out 2\>list.def.err
 		exitstatus_actual=$?
 
-		if [ "$verbose" ] ; then
+		if [ "$verbose" -ge 2 ] ; then
 			echo stdout:
 			echo _______
 			cat list.def.out
@@ -294,7 +313,7 @@ do
 			echo >&2 ______________
 			error=1
 		else
-			echo "EXITSTATUS...$exitstatus_correct correct"
+			echo >&7 "EXITSTATUS...$exitstatus_correct correct"
 		fi
 
 		# Target was built or not generate in case of error
@@ -312,7 +331,7 @@ do
 					# Check that INCONTENT is found in the built file
 					if [ -r INCONTENT ]; then
 						if grep -q -F -e "$(cat INCONTENT)" "$target" ; then
-							echo "INCONTENT...correct"
+							echo >&7 "INCONTENT...correct"
 						else
 							echo >&2 "$0: *** '$(cat INCONTENT)' must appear in generated file"
 							echo >&2 "$target:"
@@ -326,7 +345,7 @@ do
 					# Check exact content of the target file
 					if [ -r CONTENT ] ; then
 						if diff "$target" CONTENT ; then
-							echo "CONTENT...correct"
+							echo >&7 "CONTENT...correct"
 						else	
 							echo >&2 "$0: *** CONTENT error"
 							error=1
@@ -360,14 +379,14 @@ do
 				ls -l list.def.out STDOUT
 				error=1
 			else
-				echo "STDOUT...correct"
+				echo >&7 "STDOUT...correct"
 			fi
 		fi
 
 		# Check that INSTDOUT is found in the output
 		if [ -r INSTDOUT ]; then
 			if  grep <list.def.out -qF -- "$(cat INSTDOUT)" ; then
-				echo "INSTDOUT...correct"
+				echo >&7 "INSTDOUT...correct"
 			else
 				echo >&2 "$0: *** '$(cat INSTDOUT)' was not found in output"
 				echo >&2 ____ stdout:
@@ -390,7 +409,7 @@ do
 			for lineno in $(../../sh/seq $(awk '{x++} END{ print x; }' <INSTDERR)) ; do
 			   	line=$(<INSTDERR sed -e "$lineno"'!d')
 				if grep <list.def.err -qF -- "$line" ; then
-					echo "INSTDERR...correct"
+					echo >&7 "INSTDERR...correct"
 				else
 					echo >&2 "$0: *** '$line' was not found in error output"
 					echo >&2 "stderr:"
@@ -415,7 +434,7 @@ do
 				ls -l list.def.err STDERR
 				error=1
 			else
-				echo "STDERR...correct"
+				echo >&7 "STDERR...correct"
 			fi
 		fi
 
@@ -425,15 +444,15 @@ do
 				echo >&2 "$0: *** '$(cat NOTINSTDERR)' was found in error output, but should not be there"
 				error=1
 			else
-				echo "NOTINSTDERR...correct"
+				echo >&7 "NOTINSTDERR...correct"
 			fi
 		fi
 
 		# TTYSTDOUTERR
 		if { [ -r TTYSTDOUTERR ] || [ -r EXITSTATUS ]; } && ! [ -r NOTTY ]; then
 			../../sh/rm_tmps || exit 1
-			echo $CMDPREFIX ../../bin/stu.test "$CMD" '[TTY]'
-			eval $CMDPREFIX ../../sh/tty ../../bin/stu.test $CMD \>list.def.out 
+			echo >&7 $CMDPREFIX ../../bin/stu.test "$CMD" '[TTY]'
+			eval $CMDPREFIX ../../sh/tty ../../bin/stu.test $CMD \>list.def.out
 			exitstatus_actual=$?
 
 			# Exit code
@@ -441,7 +460,7 @@ do
 				echo >&2 "$0: *** Test '$file' should have returned $exitstatus_correct, but returned $exitstatus_actual [TTY]"
 				error=1
 			else
-				echo "EXITSTATUS:TTY...$exitstatus_correct correct"
+				echo >&7 "EXITSTATUS:TTY...$exitstatus_correct correct"
 			fi
 
 			# correct output
@@ -457,7 +476,7 @@ do
 					ls -l list.def.out TTYSTDOUTERR
 					error=1
 				else
-					echo "TTYSTDOUTERR...correct"
+					echo >&7 "TTYSTDOUTERR...correct"
 				fi
 			fi
 
@@ -471,7 +490,7 @@ do
 					echo >&2 _________
 					error=1
 				else
-					echo "TTY:COLOR...correct"
+					echo >&7 "TTY:COLOR...correct"
 				fi
 				
 			fi
@@ -485,17 +504,17 @@ do
 				echo >&2 "$0: *** Expected closing color code"
 				error=1
 			else
-				echo "TTY:BALANCED...correct"
+				echo >&7 "TTY:BALANCED...correct"
 			fi
 		fi
 
 		# Second invocation does nothing 
 		if [ "$exitstatus_correct" = 0 ] && [ ! -e NOSECOND ]; then
-			echo $CMDPREFIX ../../bin/stu.test "$CMD"
+			echo >&7 $CMDPREFIX ../../bin/stu.test "$CMD"
 			eval $CMDPREFIX ../../bin/stu.test $CMD \>list.def.out 2\>list.def.err 
 			grep -qF 'Targets are up to date' list.def.out 
 			if [ "$?" = 0 ] ; then
-				echo "Second invocation...correct"
+				echo >&7 "Second invocation...correct"
 			else
 				echo >&2 "$0: *** Second invocation did no result in 'Targets are up to date'"
 				echo >&2 STDOUT:
@@ -511,14 +530,14 @@ do
 			ks=$(sed -e '/^[[:space:]]*$/d' <PARALLEL)
 			for k in $ks; do
 				../../sh/rm_tmps || exit 2
-				echo $CMDPREFIX ../../bin/stu.test "$CMD" -j "$k"
+				echo >&7 $CMDPREFIX ../../bin/stu.test "$CMD" -j "$k"
 				eval $CMDPREFIX ../../bin/stu.test $CMD -j $k \>list.def.out 2\>list.def.err
 				if [ $? != 0 ]
 				then
 					echo >&2 "$0: *** Parallel stu failed for '$file' with k = $k"
 					error=1
 				else
-					echo "PARALLEL...correct"
+					echo >&7 "PARALLEL...correct"
 				fi
 			done
 		fi	
@@ -529,7 +548,7 @@ do
 
 	if [ "$error" != 0 ] ; then
 		echo "$file" >&6
-		errors=1
+		ret=1
 		[ -n "$notall" ] && { 
 			echo >&2 "[31m$0: *** Test '$file' failed [notall][m"
 			exit 1 
@@ -537,7 +556,7 @@ do
 	fi
 done
 
-echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
+output_end
 cd ..
 
 time_end=$(sh/now)
@@ -545,7 +564,7 @@ time_diff=$(expr $time_end - $time_begin)
 runtime=$(printf '%u:%02u\n' "$(expr $time_diff / 60)" "$(expr $time_diff % 60)")
 echo "Runtime:  $runtime"
 
-if [ "$errors" != 0 ]
+if [ "$ret" != 0 ]
 then
 	count_failed=$(echo $(<log/error.log wc -l))
 	success_rate=$(awk 'BEGIN{printf "%.2f\n", 100*('"$count_total"'-'"$count_failed"')/'"$count_total"'}')
diff --git a/test/1-version-double/EXEC b/test/1-version-double/EXEC
--- a/test/1-version-double/EXEC
+++ b/test/1-version-double/EXEC
@@ -10,16 +10,16 @@ STUFILE2=tmp2.stu
 error=0
 
 # Arguments:
-#   $1	 Correct exit code
+#   $1	 Correct exit status
 #   $2   Version in %version statement of file 1
 #   $3   Version in %version statement of file 2
 do_test()
 {
-	exitcode_correct="$1"
+	exitstatus_correct="$1"
 	version1="$2"
 	version2="$3"
 
-	echo >&2 "$0:  TESTING $1 $2 $3"
+	echo "$0:  TESTING $1 $2 $3"
 
 	rm -f $STUFILE1 $STUFILE2 A list.err
 
@@ -35,14 +35,14 @@ B { echo CORRECT >B }
 EOF
 
 	../../bin/stu.test -f $STUFILE1 2>list.err
-	exitcode_actual=$?
-	echo >&2 "	exitcode=$exitcode_actual"
-	if [ "$exitcode_actual" != "$exitcode_correct" ] ; then
+	exitstatus_actual=$?
+	echo "	exitstatus=$exitstatus_actual"
+	if [ "$exitstatus_actual" != "$exitstatus_correct" ] ; then
 		echo >&2 "*** $0:  Error in case $1 $2"
 		error=1
 	fi
 
-	if [ "$exitcode_correct" = 0 ] ; then
+	if [ "$exitstatus_correct" = 0 ] ; then
 		if ! grep -qF CORRECT A ; then
 			echo >&2 "*** $0:  Incorrect content of file 'A'"
 			error=1
diff --git a/test/clash/EXEC b/test/clash/EXEC
--- a/test/clash/EXEC
+++ b/test/clash/EXEC
@@ -23,17 +23,17 @@ while read -r line ; do
 	exitstatus=$?
 	[ "$exitstatus" = 2 ] || {
 		echo >&2 "*** error (a) Exit code should be 2 (logical error), but is not"
-		echo "exitstatus=$exitstatus"
+		echo >&2 "exitstatus=$exitstatus"
 		echo 1 >list.exitstatus
 		exit 1
 	}
 
 	grep -qF "'-o'" list.err || {
 		echo >&2 "*** error (b) String \"'-o'\" not found in error output"
-		echo "Content of error output:"
-		echo ________
-		cat list.err
-		echo ________
+		echo >&2 "Content of error output:"
+		echo >&2 ________
+		cat  >&2 list.err
+		echo >&2  ________
 		echo 1 >list.exitstatus || exit 1
 		exit 1
 	}
diff --git a/test/dangling/EXEC b/test/dangling/EXEC
--- a/test/dangling/EXEC
+++ b/test/dangling/EXEC
@@ -13,15 +13,15 @@ exitstatus=$?
 	exit 1
 }
 
-echo >&2 STDOUT:
-cat >&2 list.out
-echo >&2 _______
-echo >&2 STDERR:
-cat >&2 list.err
-echo >&2 _______
+echo STDOUT:
+cat  list.out
+echo _______
+echo STDERR:
+cat  list.err
+echo _______
 
 grep -qF 'Executing B' list.out || {
-	echo >&2 "*** invalid output"
+	echo >&2 "*** Invalid output"
 	exit 1
 }
 
diff --git a/test/long-fail-j-k/EXEC b/test/long-fail-j-k/EXEC
--- a/test/long-fail-j-k/EXEC
+++ b/test/long-fail-j-k/EXEC
@@ -4,7 +4,7 @@
 # (1) No options
 #
 
-echo >&2 RUN '(1)'
+echo RUN '(1)'
 
 rm -f ? || exit 2
 
@@ -12,7 +12,7 @@ rm -f ? || exit 2
 exitstatus=$?
 
 [ "$exitstatus" = 1 ] || {
-	echo >&2 "$: *** Variant without options failed (1)"
+	echo >&2 "*** Variant without options failed (1)"
 	exit 1
 }
 
@@ -20,12 +20,12 @@ exitstatus=$?
 # (2) With -k 
 #
 
-echo >&2 RUN '(2)'
+echo RUN '(2)'
 
 rm -f ? || exit 2
  
 if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" != 0 ]; then
-	echo >&2 "$0: *** There are still processes running from previously (2b)"
+	echo >&2 "*** There are still processes running from previously (2b)"
 	exit 1
 fi
 
@@ -35,25 +35,24 @@ pid=$!
 sleep 2 || exit 2
 
 if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" = 0 ]; then
-	echo >&2 "$0: *** Stu is not running (2a)"
+	echo >&2 "*** Stu is not running (2a)"
 	exit 1
 fi
 
 ps -fA | grep "$pid"
 kill -TERM "$pid"  || {
-	echo >&2 "$0: *** Kill (2)"
+	echo >&2 "*** Kill (2)"
 	exit 1
 }
 
 sleep 1 || exit 2
-
 ps -fA | grep  74634275
 ps -fA | grep  stu
 
 if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" != 0 ]; then
-	echo >&2 "$0: *** Stu is still running (2b)"
-	ps -fA | grep 74634275 | grep -v grep
-	echo _______________
+	echo >&2 "*** Stu is still running (2b)"
+	ps -fA | grep 74634275 | grep -v grep >&2
+	echo >&2 _______________
 	exit 1
 fi
 
@@ -64,15 +63,14 @@ exitstatus=$?
 # (3) With -j2
 #
 
-echo >&2 RUN '(3)'
-
+echo RUN '(3)'
 rm -f ? || exit 2
 
 ../../bin/stu.test -j2 >list.out 2>list.err
 exitstatus=$?
 
 if [ "$exitstatus" != 1 ]; then
-	echo >&2 "$: *** Variant without options failed (3)"
+	echo >&2 "*** Variant without options failed (3)"
 	exit 1
 fi
 
@@ -80,7 +78,7 @@ fi
 # (4) With -j2 -k 
 #
 
-echo >&2 RUN '(4)'
+echo RUN '(4)'
 
 rm -f ? || exit 2
  
@@ -102,7 +100,7 @@ kill -TERM "$pid" || {
 sleep 1 || exit 2
 
 if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" != 0 ]; then
-	echo >&2 "$0: *** Stu is still running (4b)"
+	echo >&2 "*** Stu is still running (4b)"
 	exit 1
 fi
 
