fix testing

diff --git a/sh/mktest b/sh/mktest
--- a/sh/mktest
+++ b/sh/mktest
@@ -485,7 +485,7 @@ printf 'Runtime: %u:%02u\n' "$(expr $time_diff / 60)" "$(expr $time_diff % 60)"
 
 if [ "$errors" != 0 ]
 then
-	echo >&2 "[31m$0: *** The following $(echo $(<../error.log wc -l)) test(s) failed:"
+	echo >&2 "[31m$0: *** The following $(echo $(<../error.log wc -l)) test(s) failed (out of $(echo $(ls -1 | wc -l))):"
 	cat ../error.log
 	printf "[m"
 	exit 1
