cov

diff --git a/sh/test b/sh/test
--- a/sh/test
+++ b/sh/test
@@ -57,7 +57,10 @@
 # TARGET       The name of the target that is built in the test, instead of the default
 #              'A'.  This does not change the invocation: Stu is invoked without arguments
 #              by default.  It only changes the check that the file was built, and its
-#              content.   May be an empty file to omit testing for an existing target.
+#              content.   May be an empty file to omit testing for an existing target.  If
+#              EXITSTATUS exists, the presence of this file means that the test should
+#              not fail when the target 'A' exists after execution (content of TARGET is
+#              ignored).
 # CMD          Additional command arguments passed to Stu.  Content may use shell quoting
 #              and escaping.  For instance, the file may contain -C ' A ' to pass an
 #              argument beginning and ending in space to Stu.
@@ -414,8 +417,10 @@ do
 			fi
 		else
 			# Make sure the file "A" was not generated
-			if [ -r A ]; then
-				test_fail "File 'A' was generated although the script failed"
+			if ! [ -r TARGET ] ; then
+				if [ -r A ]; then
+					test_fail "File 'A' was generated although the script failed"
+				fi
 			fi
 		fi
 
