PRELOAD.cc

diff --git a/sh/test b/sh/test
--- a/sh/test
+++ b/sh/test
@@ -16,15 +16,16 @@
 #	log/error.log     List of tests that failed, one name per line
 #
 # PARAMETERS
-#	$NDEBUG   Set to non-empty to test the nondebug version; by default the debug
-#	          version is tested
-#	$VARIANT  Other variant of the compiled file; the default is to take the file that
-#	          matches the value of $NDEBUG
-#	$verbose  Set to {0,1,2} for verbose levels; default is 0
-#	$notall   If non-empty, exit on the first error, instead of running everything
-#	$emptyok  Set to non-empty to *not* output an error for empty test directories;
-#	          useful after doing "rm" in a version control system on one, since that
-#	          leaves a directory containing only (e.g.) ".svn".  Ignores dotfiles.
+#	$NDEBUG      Set to non-empty to test the nondebug version; by default the debug
+#	             version is tested
+#	$VARIANT     Other variant of the compiled file; the default is to take the file that
+#	             matches the value of $NDEBUG
+#	$TEST_DEBUG  Set to {0,1,2} for verbose levels; default is 0
+#	$notall      If non-empty, exit on the first error, instead of running everything
+#	$emptyok     Set to non-empty to *not* output an error for empty test directories;
+#	             useful after doing "rm" in a version control system on one, since
+#	             that leaves a directory containing only (e.g.) ".svn".  Ignores
+#	             dotfiles.
 #
 # EXIT STATUS
 #	0         All tests succeeded
@@ -74,6 +75,8 @@
 # INSTDERR     Prescribe strings that must appear in Stu's error output
 # NOTINSTDERR  A text that must not be present in Stu's error output
 # TTYSTDOUTERR The output and error output (interleaved) when in TTY mode
+# PRELOAD.cc   If present, the file is compiled as a shared object and Stu executed with
+#              LD_PRELOAD set to that file
 # EXEC         An alternative test script; it can do anything and should return a sensible
 #              exit status (i.e., 0 on success, 1 on test failed, 2 on internal error).
 #              It also otherwise behaves like sh/test, e.g., output '***' only on error.
@@ -119,7 +122,7 @@ output_next()
 	else
 		count_failed_text="[41;30m$count_failed[m"
 	fi
-	if [ "$verbose" = 0 ] ; then
+	if [ "$TEST_DEBUG" = 0 ] ; then
 		printf '[2KTesting [%s] (%s/%s/%s) %s\r' \
 		       "$VARIANT" \
 		       "[42;30m$count_succeed[m" \
@@ -183,16 +186,18 @@ time_begin=$(sh/now)
 ret=0
 count_succeed=0
 count_failed=0
+preload_cc=log/preload.cc
+preload_so=log/preload.so
 
 mkdir -p log
 exec 6>log/error.log
 
-verbose=${verbose:-0}
-printf '%s\n' "$verbose" | grep -q -E '^[012]$' || {
-	echo >&2 "$0: *** Invalid verbosity level '$verbose'"
+TEST_DEBUG=${TEST_DEBUG:-0}
+printf '%s\n' "$TEST_DEBUG" | grep -q -E '^[012]$' || {
+	echo >&2 "$0: *** Invalid verbosity level '$TEST_DEBUG'"
 	exit 2
 }
-[ "$verbose" -ge 1 ] && exec 7>&1 || exec 7>/dev/null
+[ "$TEST_DEBUG" -ge 1 ] && exec 7>&1 || exec 7>/dev/null
 
 rm -f bin/stu.test || exit 2
 if [ "$VARIANT" ] ; then
@@ -257,15 +262,6 @@ do
 		continue
 	done
 
-	CMD=
-	if [ -r CMD ]; then
-		CMD=$(sed -e '/^[[:space:]]*$/d' <CMD)
-	fi
-	CMDPREFIX=
-	if [ -r CMDPREFIX ]; then
-		CMDPREFIX=$(sed -e '/^[[:space:]]*$/d' <CMDPREFIX)
-	fi
-
 	# The following will save:  list.def.out and list.def.err
 
 	if [ -r EXEC ]; then
@@ -273,7 +269,7 @@ do
 			-o -r STDERR -o -r NOTINSTDERR -o -r CMD -o -r CMDPREFIX \
 			-o -r TARGET -o -r INCONTENT -o -r CONTENT \
 			-o -r STDOUT -o -r NOSECOND -o -r NOTTY -o -r TTYSTDOUTERR \
-			-o -r NOCOLOR ]; then
+			-o -r NOCOLOR -o -r PRELOAD.cc ]; then
 			test_fail_fatal "EXEC does not allow any other file"
 			continue
 		fi
@@ -284,12 +280,29 @@ do
 			test_fail "EXEC failed"
 		fi
 	else
+		CMD=
+		if [ -r CMD ]; then
+			CMD=$(sed -e '/^[[:space:]]*$/d' <CMD)
+		fi
+		CMDPREFIX=
+		if [ -r CMDPREFIX ]; then
+			CMDPREFIX=$(sed -e '/^[[:space:]]*$/d' <CMDPREFIX)
+		fi
+		if [ -r PRELOAD.cc ]; then
+			echo >&7 "PRELOAD.cc found; cc=$preload_cc so=$preload_so"
+			rm -f "../../$preload_cc" "../../$preload_so" || exit 2
+			cp -- PRELOAD.cc "../../$preload_cc" || exit 2
+			$(cat ../../conf/CXX) $(cat ../../conf/CXXFLAGS) -shared -fpic \
+				"../../$preload_cc" -o "../../$preload_so" || exit 2
+			CMDPREFIX="LD_PRELOAD=../../$preload_so $CMDPREFIX"
+		fi
+
 		# Execute command
 		echo >&7 $CMDPREFIX ../../bin/stu.test "$CMD"
 		eval $CMDPREFIX ../../bin/stu.test $CMD \>list.def.out 2\>list.def.err
 		exitstatus_actual=$?
 
-		if [ "$verbose" -ge 2 ] ; then
+		if [ "$TEST_DEBUG" -ge 2 ] ; then
 			echo stdout:
 			echo _______
 			cat list.def.out
@@ -539,7 +552,7 @@ if [ "$ret" != 0 ] ; then
 	else
 		count_failed_text="[41;30m$count_failed[m"
 	fi
-	if [ "$verbose" = 0 ] ; then
+	if [ "$TEST_DEBUG" = 0 ] ; then
 		printf '[2KTesting done [%s] (%s/%s/%s)\n' \
 		       "$VARIANT" \
 		       "[42;30m$count_succeed[m" \
