test log

diff --git a/sh/test b/sh/test
--- a/sh/test
+++ b/sh/test
@@ -155,7 +155,7 @@ output_end()
 
 output_success()
 {
-	echo "[32mTesting [$VARIANT] successful[m"
+	echo "[32mTesting [$VARIANT] Success[m"
 }
 
 ret=0
@@ -212,7 +212,7 @@ do
 	file=$(echo "$file" | sed -e 's,^tests/,,')
 
 	if [ ! -d "$file" ]; then
-		echo >&2 "$0: *** '$file' is not a directory"
+		echo >&2 "$0: ($file) *** '$file' is not a directory"
 		ret=1
 		echo "$file" >&6
 		continue
@@ -221,7 +221,7 @@ do
 	# There are no files in the test directory (ignoring dotfiles) 
 	if [ "$(echo $(ls -1 "$file" | wc -l))" = 0 ] ; then
 		if [ "$emptyok" != 1 ] ; then
-			echo >&2 "$0: *** Test directory $file/ does not contain any files"
+			echo >&2 "$0: ($file) *** Test directory $file/ does not contain any files"
 			ret=1
 			echo "$file" >&6
 			continue
@@ -238,7 +238,7 @@ do
 	for otherfile in $(ls -1 | sed -e '/^[A-Z]*$/!d')
 	do
 		if expr "$allowed" : ".*,$otherfile,.*" >/dev/null ; then continue ; fi
-		echo >&2 "$0: *** Invalid file '$otherfile' in test directory"
+		echo >&2 "$0: ($file) *** Invalid file '$otherfile' in test directory"
 		error=1
 	done
 
@@ -258,7 +258,7 @@ do
 			-o -r STDERR -o -r NOTINSTDERR -o -r CMD -o -r CMDPREFIX \
 			-o -r TARGET -o -r INCONTENT -o -r CONTENT \
 			-o -r STDOUT -o -r NOSECOND -o -r NOTTY -o -r TTYSTDOUTERR -o -r NOCOLOR ]; then
-			echo >&2 "$0: *** EXEC does not allow any other file"
+			echo >&2 "$0: ($file) *** EXEC does not allow any other file"
 			ret=1
 			echo "$file" >&6
 			continue
@@ -267,7 +267,7 @@ do
 		echo >&7 ./EXEC
 		./EXEC 1>&7
 		if [ "$?" != 0 ]; then
-			echo >&2 "$0: *** EXEC failed"
+			echo >&2 "$0: ($file) *** EXEC failed"
 			error=1
 		fi
 	else
@@ -304,12 +304,12 @@ do
 			}
 			exitstatus_correct=$(sed -e '/^[[:space:]]*$/d;s/[[:space:]]\{1,\}//g' <EXITSTATUS)
 			if [ "$exitstatus_correct" = 0 ]; then
-				echo >&2 "$0: *** Content of EXITSTATUS should not be zero"
+				echo >&2 "$0: ($file) *** Content of EXITSTATUS should not be zero"
 				error=1
 			fi
 		fi
 		if [ "$exitstatus_actual" != "$exitstatus_correct" ]; then
-			echo >&2 "$0: *** Test '$file' should have returned $exitstatus_correct, but returned $exitstatus_actual"
+			echo >&2 "$0: ($file) *** Test '$file' should have returned $exitstatus_correct, but returned $exitstatus_actual"
 			echo >&2 list.def.out:
 			echo >&2 ______________
 			cat >&2 list.def.out
@@ -332,7 +332,7 @@ do
 			fi
 			if [ -n "$target" ] ; then
 				if [ ! -r "$target" ]; then  # The main target must have been built
-					echo >&2 "$0: *** Target '$target' was not built"
+					echo >&2 "$0: ($file) *** Target '$target' was not built"
 					error=1
 				else
 					# Check that INCONTENT is found in the built file
@@ -340,7 +340,7 @@ do
 						if grep -q -F -e "$(cat INCONTENT)" "$target" ; then
 							echo >&7 "INCONTENT...correct"
 						else
-							echo >&2 "$0: *** '$(cat INCONTENT)' must appear in generated file"
+							echo >&2 "$0: ($file) *** '$(cat INCONTENT)' must appear in generated file"
 							echo >&2 "$target:"
 							echo >&2 ____
 							cat "$target"
@@ -354,21 +354,21 @@ do
 						if diff "$target" CONTENT ; then
 							echo >&7 "CONTENT...correct"
 						else	
-							echo >&2 "$0: *** CONTENT error"
+							echo >&2 "$0: ($file) *** CONTENT error"
 							error=1
 						fi
 					fi
 				fi
 			else
 				if [ -r INCONTENT ] || [ -r CONTENT ] ; then
-					echo >&2 "$0: *** CONTENT and INCONTENT must not appear in conjunction with an empty TARGET"
+					echo >&2 "$0: ($file) *** CONTENT and INCONTENT must not appear in conjunction with an empty TARGET"
 					error=1
 				fi
 			fi
 		else
 			# Make sure the file "A" was not generated
 			if [ -r A ]; then
-				echo >&2 "$0: *** File 'A' was generated although the script failed"
+				echo >&2 "$0: ($file) *** File 'A' was generated although the script failed"
 				error=1
 			fi
 		fi
@@ -378,12 +378,12 @@ do
 			diff list.def.out STDOUT
 			exitstatus=$?
 			if [ "$exitstatus" != 0 ] ; then
-				echo >&2 "$0: *** output does not match 'STDOUT'"
+				echo >&2 "$0: ($file) *** output does not match 'STDOUT'"
 				echo >&2 '_____ actual output:'
-				cat list.def.out
+				cat  >&2 list.def.out
 				echo >&2 _____
-				wc -l list.def.out STDOUT
-				ls -l list.def.out STDOUT
+				>&2 wc -l list.def.out STDOUT
+				>&2 ls -l list.def.out STDOUT
 				error=1
 			else
 				echo >&7 "STDOUT...correct"
@@ -395,9 +395,9 @@ do
 			if  grep <list.def.out -qF -- "$(cat INSTDOUT)" ; then
 				echo >&7 "INSTDOUT...correct"
 			else
-				echo >&2 "$0: *** '$(cat INSTDOUT)' was not found in output"
+				echo >&2 "$0: ($file) *** '$(cat INSTDOUT)' was not found in output"
 				echo >&2 ____ stdout:
-				cat >&2 list.def.out
+				cat  >&2 list.def.out
 				echo >&2 ____
 				error=1
 			fi
@@ -406,7 +406,7 @@ do
 		# Check that at least one line of error message is generated 
 		if [ "$exitstatus_correct" != 0 ] && [ \! -r STDERR ]; then
 			if [ \! \( "$(echo $(cat list.def.err | wc -l))" -gt 0 \) ]; then
-				echo >&2 "$0: *** Nothing written to stderr although exit status is >0"
+				echo >&2 "$0: ($file) *** Nothing written to stderr although exit status is >0"
 				error=1
 			fi
 		fi
@@ -418,10 +418,10 @@ do
 				if grep <list.def.err -qF -- "$line" ; then
 					echo >&7 "INSTDERR...correct"
 				else
-					echo >&2 "$0: *** '$line' was not found in error output"
+					echo >&2 "$0: ($file) *** '$line' was not found in error output"
 					echo >&2 "stderr:"
 					echo >&2 ______
-					cat >&2 list.def.err
+					cat  >&2 list.def.err
 					echo >&2 ______
 					error=1
 				fi
@@ -433,7 +433,7 @@ do
 			diff list.def.err STDERR
 			exitstatus=$?
 			if [ "$exitstatus" != 0 ]; then
-				echo >&2 "$0: *** error output does not match 'STDERR'"
+				echo >&2 "$0: ($file) *** error output does not match 'STDERR'"
 				echo >&2 '_____ actual error output:'
 				cat list.def.err
 				echo >&2 _____
@@ -448,7 +448,7 @@ do
 		# Check that NOTINSTDERR is not found in the error output
 		if [ -r NOTINSTDERR ]; then
 			if grep -q -F -e "$(cat NOTINSTDERR)" list.def.err ; then
-				echo >&2 "$0: *** '$(cat NOTINSTDERR)' was found in error output, but should not be there"
+				echo >&2 "$0: ($file) *** '$(cat NOTINSTDERR)' was found in error output, but should not be there"
 				error=1
 			else
 				echo >&7 "NOTINSTDERR...correct"
@@ -464,7 +464,7 @@ do
 
 			# Exit code
 			if [ "$exitstatus_actual" != "$exitstatus_correct" ]; then
-				echo >&2 "$0: *** Test '$file' should have returned $exitstatus_correct, but returned $exitstatus_actual [TTY]"
+				echo >&2 "$0: ($file) *** Test '$file' should have returned $exitstatus_correct, but returned $exitstatus_actual [TTY]"
 				error=1
 			else
 				echo >&7 "EXITSTATUS:TTY...$exitstatus_correct correct"
@@ -475,7 +475,7 @@ do
 				diff list.def.out TTYSTDOUTERR
 				exitstatus=$?
 				if [ "$exitstatus" != 0 ]; then
-					echo >&2 "$0: *** TTY error output does not match 'TTYSTDOUTERR'"
+					echo >&2 "$0: ($file) *** TTY error output does not match 'TTYSTDOUTERR'"
 					echo >&2 '_____ actual output:'
 					cat list.def.out
 					echo >&2 _____
@@ -490,7 +490,7 @@ do
 			# There is color
 			if [ -r EXITSTATUS ] && ! [ -r NOCOLOR ] ; then
 				if ! grep -qE '' list.def.out ; then
-					echo >&2 "$0: *** Expected ESC in TTY output because EXITSTATUS exists"
+					echo >&2 "$0: ($file) *** Expected ESC in TTY output because EXITSTATUS exists"
 					echo >&2 output:
 					echo >&2 _________
 					cat >&2 list.def.out
@@ -508,7 +508,7 @@ do
 				# allow a color code to be replaced by
 				# another one directly: 
 				#      grep -qE '[^0]+m[^]*[^0]+m' list.def.out 
-				echo >&2 "$0: *** Expected closing color code"
+				echo >&2 "$0: ($file) *** Expected closing color code"
 				error=1
 			else
 				echo >&7 "TTY:BALANCED...correct"
@@ -523,7 +523,7 @@ do
 			if [ "$?" = 0 ] ; then
 				echo >&7 "Second invocation...correct"
 			else
-				echo >&2 "$0: *** Second invocation did no result in 'Targets are up to date'"
+				echo >&2 "$0: ($file) *** Second invocation did no result in 'Targets are up to date'"
 				echo >&2 STDOUT:
 				echo >&2 _____
 				cat >&2 list.def.out
@@ -541,7 +541,7 @@ do
 				eval $CMDPREFIX ../../bin/stu.test $CMD -j $k \>list.def.out 2\>list.def.err
 				if [ $? != 0 ]
 				then
-					echo >&2 "$0: *** Parallel stu failed for '$file' with k = $k"
+					echo >&2 "$0: ($file) *** Parallel stu failed for '$file' with k = $k"
 					error=1
 				else
 					echo >&7 "PARALLEL...correct"
@@ -557,7 +557,7 @@ do
 		echo "$file" >&6
 		ret=1
 		[ -n "$notall" ] && { 
-			echo >&2 "[31m$0: *** Test '$file' failed [notall][m"
+			echo >&2 "[31m$0: ($file) *** Test '$file' failed [notall][m"
 			exit 1 
 		}
 	fi
@@ -582,7 +582,7 @@ then
 fi
 
 output_success
-if [ -z "$1" ] && [ -z "$VARIANT" ] && [ "$NDEBUG" ] ; then
+if [ -z "$1" ] && [ "$VARIANT" = ndebug ] ; then
 	echo >>test.runtime "$(date +%Y-%m-%dT%H:%M:%S) $(printf %s "$(cat VERSION)") $runtime" 
 fi
 exit 0
