2.10.17 don't include escape characers in the source code

diff --git a/sh/test b/sh/test
--- a/sh/test
+++ b/sh/test
@@ -124,6 +124,7 @@
 # Note:  we can't use "set -e" here (which is a good general practice in shell scripts),
 # because otherwise we can't use $? to check the exit code of Stu.
 
+esc=$(printf '\033')
 ALLOWED_FILES='EXITSTATUS INSTDOUT INSTDERR NOTINSTDERR STDERR TTYSTDOUTERR INTTYSTDOUTERR CMD CMDPREFIX TARGET INCONTENT NOTINCONTENT CONTENT EXEC STDOUT NOSECOND NOTTY NOCOLOR COV_TAG VARIANT'
 error_file=${TMPDIR:-/tmp}/test.$$.error
 
@@ -134,13 +135,13 @@ output_next()
 	if [ "$count_failed" = 0 ] ; then
 		count_failed_text=0
 	else
-		count_failed_text="[41;30m$count_failed[m"
+		count_failed_text="$esc[41;30m$count_failed$esc[m"
 	fi
 	if [ "$TEST_VERBOSE" = 0 ] ; then
-		printf '[2KTesting [%s] (%s/%s/%s) %s\r' \
+		printf "$esc"'[2KTesting [%s] (%s/%s/%s) %s\r' \
 		       "$VARIANT$subset" \
-		       "[42;30m$count_succeed[m" \
-		       "[43;30m$((count_total - count_succeed - count_failed))[m" \
+		       "$esc[42;30m$count_succeed$esc[m" \
+		       "$esc[43;30m$((count_total - count_succeed - count_failed))$esc[m" \
 		       "$count_failed_text" \
 		       "$file"
 	fi
@@ -153,7 +154,7 @@ output_end()
 
 output_success()
 {
-	echo "[2K[32mTesting [$VARIANT$subset] Success ($count_total tests) (runtime $runtime)[m"
+	echo "$esc[2K$esc[32mTesting [$VARIANT$subset] Success ($count_total tests) (runtime $runtime)$esc[m"
 }
 
 test_fail()
@@ -167,7 +168,7 @@ test_fail_fatal_no_cd()
 	echo >&2 "$0: ($file) *** $1"
 	echo "$file" >&6
 	[ "$notall" ] && {
-		echo >&2 "[31m$0: ($file) *** Test '$file' failed [notall][m"
+		echo >&2 "$esc[31m$0: ($file) *** Test '$file' failed [notall]$esc[m"
 		exit 1
 	}
 	ret=1
@@ -562,7 +563,7 @@ do
 			fi
 
 			if [ -r EXITSTATUS ] && ! grep -q -F -e 5 EXITSTATUS && ! [ -r NOCOLOR ] ; then
-				if ! grep -q -E -e '' list.def.out ; then
+				if ! grep -q -E -e "$esc" list.def.out ; then
 					test_fail "Expected ESC in TTY output because EXITSTATUS exists"
 					>&2 echo output:
 					>&2 printf '/---------\n'
@@ -574,7 +575,7 @@ do
 				fi
 			fi
 
-			if grep -qE -e '[[](32|1|35|31)m[^]*$' list.def.out ; then
+			if grep -qE -e "$esc"'[[](32|1|35|31)m[^'"$esc"']*$' list.def.out ; then
 				test_fail "Expected closing escape sequence after opening escape sequence in stdout"
 				>&2 echo output:
 				>&2 printf '/---------\n'
@@ -621,19 +622,19 @@ if [ "$ret" != 0 ] ; then
 	if [ "$count_failed" = 0 ] ; then
 		count_failed_text=0
 	else
-		count_failed_text="[41;30m$count_failed[m"
+		count_failed_text="$esc[41;30m$count_failed$esc[m"
 	fi
 	if [ "$TEST_VERBOSE" = 0 ] ; then
-		printf '[2KTesting done [%s] (%s/%s/%s)\n' \
+		printf "$esc"'[2KTesting done [%s] (%s/%s/%s)\n' \
 		       "$VARIANT" \
-		       "[42;30m$count_succeed[m" \
-		       "[43;30m$((count_total - count_succeed - count_failed))[m" \
+		       "$esc[42;30m$count_succeed$esc[m" \
+		       "$esc[43;30m$((count_total - count_succeed - count_failed))$esc[m" \
 		       "$count_failed_text"
 	fi
 	echo >&2 Failed tests:
 	cat  >&2 log/error.log
 	success_rate=$(awk 'BEGIN{printf "%.2f\n", 100*('"$count_total"'-'"$count_failed"')/'"$count_total"'}')
-	echo >&2 "[31m$0: *** ${success_rate}% success rate.  $count_failed test(s) failed (out of $count_total).[m"
+	echo >&2 "$esc[31m$0: *** ${success_rate}% success rate.  $count_failed test(s) failed (out of $count_total).$esc[m"
 fi
 
 if [ -z "$1" ] ; then
