test_clean:  find_newline_eof()

diff --git a/sh/test_clean b/sh/test_clean
--- a/sh/test_clean
+++ b/sh/test_clean
@@ -7,24 +7,20 @@ find_source_files()
 	find tests -name EXEC
 }
 
-check_double_slash()
+check_newline_eof()
 {
-	grep -E -n '(^|[^:])//' src/*.cc src/*.hh |
-	sed -e 's,^\([^:]*:[0-9]*:\).*$,\1 C++ source must not contain //,' |
-	grep -E '.' >&2 && return 1
-	return 0
-}
-
-check_double_hash()
-{
-	find . -type f -a \( -name '*.stu' -o -perm -u+x -o -name Makefile \) -a \! -name '*~' \
-	     -a \! -path './.git*' -a \! -path './bin/stu.*' -a \! -path './bin/stu' \
-	     -a \! -path './config*' -a \! -path './build-aux/*' -a \! -path devel/TODO.stu |
-		xargs grep -F -n '#''#' && {
-		echo >&2 "*** Shell scripts, makefiles and Stu scripts must not contain #""#"
-		return 1
+	find_source_files | {
+		my_ret=0
+		while read file ; do
+			[ -s "$file" ] || continue
+			has_newline_eof=$(echo $(tail -c-1 -- "$file" | wc -l))
+			if [ "$has_newline_eof" = 0 ] ; then
+				echo >&2 "$file:$((1 + $(wc -l <"$file"))): newline missing at end of file"
+				my_ret=1
+			fi
+		done
+		return "$my_ret"
 	}
-	return 0
 }
 
 check_space_file()
@@ -75,7 +71,7 @@ BEGIN {
 	return 0
 }
 
-check_forbidden_tab()
+check_midline_tab()
 {
 	find_source_files |
 		xargs grep -E -n -e '[^'"$(printf '\t')"'#*]'"$(printf '\t')" |
@@ -86,6 +82,15 @@ check_forbidden_tab()
 	return 0
 }
 
+check_manpage_tab()
+{
+	grep -F -n -e "$(printf '\t')" man/stu.1.in && {
+		echo >&2 "*** 'man/stu.1.in' must not contain tabs"
+		return 1
+	}
+	return 0
+}
+
 check_backtick()
 {
 	find_source_files |
@@ -93,6 +98,26 @@ check_backtick()
 		xargs grep -E -n -e '`' |
 		sed -e 's,^\([^:]*:[0-9]*:\).*$,\1 File must not contain backtick "`",' |
 		grep -E '.' >&2 && return 1
+	return 0
+}
+
+check_double_slash()
+{
+	grep -E -n '(^|[^:])//' src/*.cc src/*.hh |
+	sed -e 's,^\([^:]*:[0-9]*:\).*$,\1 C++ source must not contain //,' |
+	grep -E '.' >&2 && return 1
+	return 0
+}
+
+check_double_hash()
+{
+	find . -type f -a \( -name '*.stu' -o -perm -u+x -o -name Makefile \) -a \! -name '*~' \
+	     -a \! -path './.git*' -a \! -path './bin/stu.*' -a \! -path './bin/stu' \
+	     -a \! -path './config*' -a \! -path './build-aux/*' -a \! -path devel/TODO.stu |
+		xargs grep -F -n '#''#' && {
+		echo >&2 "*** Shell scripts, makefiles and Stu scripts must not contain #""#"
+		return 1
+	}
 	return 0
 }
 
@@ -113,11 +138,11 @@ check_assert_false()
 	return 0
 }
 
+check_sed()
 # Check that we don't use sed with the -E or -r option.  '-r' is a GNU extension that
 # enabled extended regular expressions.  POSIX does not prescribe an "extended regexp"
 # mode for sed.  In many implementations, '-E' does the same.  '-E' is more portable than
 # '-r', but still not POSIX.
-check_sed()
 {
 	find . -type f -a \! -path './.git*' -a \! -name '*~' |
 		xargs grep -n -E -e 'sed[[:space:]]+-[Er]' |
@@ -135,28 +160,20 @@ check_test_nolong_sleep()
 	return 0
 }
 
-check_manpage_tab()
-{
-	grep -F -n -e "$(printf '\t')" man/stu.1.in && {
-		echo >&2 "*** 'man/stu.1.in' must not contain tabs"
-		return 1
-	}
-	return 0
-}
-
 ret=0
 
-check_double_slash || ret=1
-check_double_hash || ret=1
+check_newline_eof || ret=1
 check_space_file || ret=1
 check_space_line || ret=1
 check_double_empty_line || ret=1
-check_forbidden_tab || ret=1
+check_midline_tab || ret=1
+check_manpage_tab || ret=1
 check_backtick || ret=1
+check_double_slash || ret=1
+check_double_hash || ret=1
 check_control || ret=1
 check_assert_false || ret=1
 check_sed || ret=1
 check_test_nolong_sleep || ret=1
-check_manpage_tab || ret=1
 
 exit "$ret"
