fix quoting error in output; fix tests; add // test

diff --git a/test/continue-dependency-not-found/EXEC b/test/continue-dependency-not-found/EXEC
--- a/test/continue-dependency-not-found/EXEC
+++ b/test/continue-dependency-not-found/EXEC
@@ -8,13 +8,13 @@ echo ../../stu
 ../../stu -k >list.out 2>list.err
 exitcode="$?"
 if [ "$exitcode" != 1 ] ; then
-    echo >&2 "$0:  *** stu did not fail (run A)"
-    exit 1
+	echo >&2 "$0:  *** stu did not fail (run A)"
+	exit 1
 fi
 
-fgrep -v 'not exist' list.err || {
-    echo "$0:  *** error output not correct (run A)"
-    exit 1
+grep -qF 'not exist' list.err && {
+	echo "$0:  *** error output not correct (run A)"
+	exit 1
 }
 
 doo rm -f ?
@@ -23,23 +23,23 @@ echo ../../stu -k
 ../../stu -k >list.out 2>list.err
 exitcode="$?"
 if [ "$exitcode" != 1 ] ; then
-    echo >&2 "$0:  *** stu did not have exit code 1 (run B)"
-    exit 1
+	echo >&2 "$0:  *** stu did not have exit code 1 (run B)"
+	exit 1
 fi
 
-fgrep CORRECT B || {
-    echo >&2 "$0:  *** file 'B' not correctly built (run B)"
-    exit 1
+grep -Fq CORRECT B || {
+	echo >&2 "$0:  *** file 'B' not correctly built (run B)"
+	exit 1
 }
 
-fgrep -v "no rule to build 'nonexistingfile'" list.err || {
-    echo "$0:  *** error output does not contain \"no rule to build 'nonexistingfile'\" (run B)"
-    exit 1
+grep -Fq "no rule to build 'nonexistingfile'" list.err || {
+	echo "$0:  *** error output does not contain \"no rule to build 'nonexistingfile'\" (run B)"
+	exit 1
 }
 
-fgrep -v '*** targets not remade because of errors' list.err || {
-    echo "$0:  *** error output does not contain 'targets not remade because of errors' (run B)"
-    exit 1
+grep -Fq '*** Targets not rebuilt because of errors' list.err || {
+	echo "$0:  *** error output does not contain 'targets not remade because of errors' (run B)"
+	exit 1
 }
 
 exit 0
diff --git a/test/existence-only-dependency-parameters/EXEC b/test/existence-only-dependency-parameters/EXEC
--- a/test/existence-only-dependency-parameters/EXEC
+++ b/test/existence-only-dependency-parameters/EXEC
@@ -7,25 +7,25 @@ doo rm -rf data-X-dir
 echo >&2 ../../stu 
 ../../stu 
 if [ "$?" != 0 ]; then
-    echo "$0:  *** first stu failed"
-    exit 1
+	echo "$0:  *** first stu failed"
+	exit 1
 fi
 
 echo >&2 touch data-X-dir/unrelatedfile
 touch data-X-dir/unrelatedfile || {
-    exit 1
+	exit 1
 }
 
 echo >&2 ../../stu
 ../../stu >list.output
 if [ "$?" != 0 ]; then
-    exit 1
+	exit 1
 fi
 
-if fgrep -v 'Nothing to be done' list.output ; then
-    echo >&2 "$0:  *** stu did not output 'Nothing to be done'"
-    exit 1
-fi
+grep -Fq 'Nothing to be done' list.output || {
+	echo >&2 "$0:  *** stu did not output 'Nothing to be done'"
+	exit 1
+}
 
 doo rm -rf data-X-dir list.output A list.*
 
