tests

diff --git a/test/continue-dependency-not-found/EXEC b/test/continue-dependency-not-found/EXEC
--- a/test/continue-dependency-not-found/EXEC
+++ b/test/continue-dependency-not-found/EXEC
@@ -4,40 +4,40 @@ doo() { echo "$@" ; "$@" ; }
 
 doo rm -f ?
 
-echo ../../stu
-../../stu -k >list.out 2>list.err
+echo ../../stu.test
+../../stu.test -k >list.out 2>list.err
 exitcode="$?"
 if [ "$exitcode" != 1 ] ; then
-	echo >&2 "$0:  *** stu did not fail (run A)"
+	echo >&2 "$0:  *** Stu did not fail (run A)"
 	exit 1
 fi
 
 grep -qF 'not exist' list.err && {
-	echo "$0:  *** error output not correct (run A)"
+	echo "$0:  *** Error output not correct (run A)"
 	exit 1
 }
 
 doo rm -f ?
 
-echo ../../stu -k
-../../stu -k >list.out 2>list.err
+echo ../../stu.test -k
+../../stu.test -k >list.out 2>list.err
 exitcode="$?"
 if [ "$exitcode" != 1 ] ; then
-	echo >&2 "$0:  *** stu did not have exit code 1 (run B)"
+	echo >&2 "$0:  *** Stu did not have exit code 1 (run B)"
 	exit 1
 fi
 
 grep -Fq CORRECT B || {
-	echo >&2 "$0:  *** file 'B' not correctly built (run B)"
+	echo >&2 "$0:  *** File 'B' not correctly built (run B)"
 	exit 1
 }
 
-grep -Fq "no rule to build 'nonexistingfile'" list.err || {
-	echo "$0:  *** error output does not contain \"no rule to build 'nonexistingfile'\" (run B)"
+grep -qF "no rule to build 'nonexistingfile'" list.err || {
+	echo "$0:  *** Error output does not contain \"no rule to build 'nonexistingfile'\" (run B)"
 	exit 1
 }
 
-grep -Fq '*** Targets not rebuilt because of errors' list.err || {
+grep -qF '*** Targets not rebuilt because of errors' list.err || {
 	echo "$0:  *** error output does not contain 'targets not remade because of errors' (run B)"
 	exit 1
 }
diff --git a/test/option-f-empty/EXEC b/test/option-f-empty/EXEC
--- a/test/option-f-empty/EXEC
+++ b/test/option-f-empty/EXEC
@@ -1,16 +1,16 @@
 #! /bin/sh
 
-../../stu -f '' 2>list.err
+../../stu.test -f '' 2>list.err
 exitcode="$?"
 
-if [ "$exitcode" != 4 ]; then
-	echo >&2 "*** Wrong exit code"
+[ "$exitcode" = 4 ] || {
+	echo >&2 "*** Exit code"
 	exit 1
-fi
+}
 
-if ! grep -Fq "./stu: *** Option -f must take non-empty argument" list.err ; then
-	echo >&2 "*** Missing error message"
+grep -qF "../../stu.test: *** Option -f must take non-empty argument" list.err || {
+	echo >&2 "*** Error output"
 	exit 1
-fi
+}
 
 exit 0
diff --git a/test/options/EXEC b/test/options/EXEC
--- a/test/options/EXEC
+++ b/test/options/EXEC
@@ -1,9 +1,7 @@
 #! /bin/sh
 
-doo() { echo "$@" ; "$@" ; }
-
 rmall() {
-    doo rm -f files list.*
+	rm -f files list.*
 }
 
 #
@@ -12,23 +10,22 @@ rmall() {
 
 rmall
 
-echo ../../stu
-../../stu >list.out 2>list.err
+../../stu.test >list.out 2>list.err
 exitcode="$?"
 
 if [ "$exitcode" != 1 ]; then
-    echo >&2 "*** Wrong exit code $exitcode (A)"
-    exit 1
+	echo >&2 "*** Wrong exit code $exitcode (A)"
+	exit 1
 fi
 
 if ! fgrep -q "main.stu:29:5: command for 'list.2' failed" list.err ; then
-    echo >&2 "*** Wrong error output (A)"
-    exit 1
+	echo >&2 "*** Wrong error output (A)"
+	exit 1
 fi
 
 if [ -r list.3 ]; then
-    echo "*** File 'list.3' should not exist (A)"
-    exit 1
+	echo "*** File 'list.3' should not exist (A)"
+	exit 1
 fi
 
 #
@@ -37,28 +34,27 @@ fi
 
 rmall
 
-echo ../../stu -k
-../../stu -k >list.out 2>list.err
+../../stu.test -k >list.out 2>list.err
 exitcode="$?"
 
 if [ "$exitcode" != 1 ]; then
-    echo >&2 "*** Wrong exit code $exitcode (B)"
-    exit 1
+	echo >&2 "*** Wrong exit code $exitcode (B)"
+	exit 1
 fi
 
 if ! fgrep -q "main.stu:29:5: command for 'list.2' failed" list.err ; then
-    echo >&2 "*** Wrong error output (B1)"
-    exit 1
+	echo >&2 "*** Wrong error output (B1)"
+	exit 1
 fi
 
 if ! fgrep -q "*** Targets not rebuilt because of errors" list.err ; then
-    echo >&2 "*** Wrong error output (B2)"
-    exit 1
+	echo >&2 "*** Wrong error output (B2)"
+	exit 1
 fi
 
 if [ \! -r list.3 ]; then
-    echo "*** File 'list.3' should exist (B)"
-    exit 1
+	echo "*** File 'list.3' should exist (B)"
+	exit 1
 fi
 
 #
@@ -67,28 +63,27 @@ fi
 
 rmall
 
-echo ../../stu -j5
-../../stu -j5 >list.out 2>list.err
+../../stu.test -j5 >list.out 2>list.err
 exitcode="$?"
 
 if [ "$exitcode" != 1 ]; then
-    echo >&2 "*** Wrong exit code $exitcode (C)"
-    exit 1
+	echo >&2 "*** Wrong exit code $exitcode (C)"
+	exit 1
 fi
 
 if ! fgrep -q "main.stu:29:5: command for 'list.2' failed" list.err ; then
-    echo >&2 "*** Wrong error output (C1)"
-    exit 1
+	echo >&2 "*** Wrong error output (C1)"
+	exit 1
 fi
 
 if fgrep -q "*** Targets not rebuilt because of errors" list.err ; then
-    echo >&2 "*** Wrong error output (C2)"
-    exit 1
+	echo >&2 "*** Wrong error output (C2)"
+	exit 1
 fi
 
 if [ \! -r list.3 ]; then
-    echo "*** File 'list.3' should exist (C)"
-    exit 1
+	echo "*** File 'list.3' should exist (C)"
+	exit 1
 fi
 
 #
@@ -97,28 +92,28 @@ fi
 
 rmall
 
-echo ../../stu -j5 -k
-../../stu -j5 -k >list.out 2>list.err
+echo ../../stu.test -j5 -k
+../../stu.test -j5 -k >list.out 2>list.err
 exitcode="$?"
 
 if [ "$exitcode" != 1 ]; then
-    echo >&2 "*** Wrong exit code $exitcode (D)"
-    exit 1
+	echo >&2 "*** Wrong exit code $exitcode (D)"
+	exit 1
 fi
 
 if ! fgrep -q "main.stu:29:5: command for 'list.2' failed" list.err ; then
-    echo >&2 "*** Wrong error output (D1)"
-    exit 1
+	echo >&2 "*** Wrong error output (D1)"
+	exit 1
 fi
 
 if ! fgrep -q "*** Targets not rebuilt because of errors" list.err ; then
-    echo >&2 "*** Wrong error output (D2)"
-    exit 1
+	echo >&2 "*** Wrong error output (D2)"
+	exit 1
 fi
 
 if [ \! -r list.3 ]; then
-    echo "*** File 'list.3' should exist (D)"
-    exit 1
+	echo "*** File 'list.3' should exist (D)"
+	exit 1
 fi
 
 #
