"Targets are up to date"

diff --git a/test/pass/EXEC b/test/pass/EXEC
--- a/test/pass/EXEC
+++ b/test/pass/EXEC
@@ -70,8 +70,8 @@ while read -r line ; do
 	}
 
 	# Check that nothing is done
-	grep -qxF 'Nothing to be done' list.out || {
-		echo >&2 "*** (4) Missing 'Nothing to be done'"
+	grep -qxF 'Targets are up to date' list.out || {
+		echo >&2 "*** (4) Missing 'Targets are up to date'"
 		exit 1
 	}
 
@@ -100,8 +100,8 @@ while read -r line ; do
 	}
 
 	# Check that something is done
-	grep -qF 'Nothing to be done' list.out && {
-		echo >&2 "*** (6) Erroneous 'Nothing to be done'"
+	grep -qFx 'Targets are up to date' list.out && {
+		echo >&2 "*** (6) Erroneous 'Targets are up to date'"
 		exit 1
 	}
 
@@ -136,8 +136,8 @@ while read -r line ; do
 	}
 
 	# Check that something is done
-	grep -qF 'Nothing to be done' list.out && {
-		echo >&2 "*** (9) Erroneous 'Nothing to be done'"
+	grep -qFx 'Targets are up to date' list.out && {
+		echo >&2 "*** (9) Erroneous 'Targets are up to date'"
 		exit 1
 	}
 
diff --git a/test/triv-1/EXEC b/test/triv-1/EXEC
--- a/test/triv-1/EXEC
+++ b/test/triv-1/EXEC
@@ -9,8 +9,8 @@ touch B
 
 ../../stu.test >list.out 2>list.err
 
-grep -qF 'Nothing to be done' list.out || {
-	echo >&2 "*** Missing 'Nothing to be done'"
+grep -qFx 'Targets are up to date' list.out || {
+	echo >&2 "*** Missing 'Targets are up to date'"
 	exit 1
 }
 
diff --git a/test/update-through-transient/EXEC b/test/update-through-transient/EXEC
--- a/test/update-through-transient/EXEC
+++ b/test/update-through-transient/EXEC
@@ -1,8 +1,6 @@
 #! /bin/sh
 
-doo() { echo "$@" ; "$@" ; }
-
-doo rm -Rf BBB A
+rm -Rf BBB A || exit 1
 
 echo CORRECT >BBB
 
@@ -23,8 +21,8 @@ echo ../../stu.test
 	exit 1
 }
 
-grep -qF 'Nothing to be done' list.content || {
-	echo >&2 "$0:  *** 'Nothing to be done' not found in output'"
+grep -qFx 'Targets are up to date' list.content || {
+	echo >&2 "$0:  *** 'Targets are up to date' not found in output'"
 	exit 1
 }
 
@@ -48,11 +46,11 @@ echo ../../stu.test
 	exit 1
 }
 
-grep -qF 'Nothing to be done' list.content || {
-	echo >&2 "$0:  *** 'Nothing to be done' not found in output'"
+grep -qFx 'Targets are up to date' list.content || {
+	echo >&2 "$0:  *** 'Targets are up to date' not found in output'"
 	exit 1
 }
 
-rm -f BBB
+rm -f BBB || exit 1
 
 exit 0
