avoid sed -r

diff --git a/test/no-command-older/EXEC b/test/no-command-older/EXEC
--- a/test/no-command-older/EXEC
+++ b/test/no-command-older/EXEC
@@ -1,7 +1,7 @@
 #! /bin/sh
 
 now="$(LC_ALL=C date)"
-year="$(echo $now | sed -re 's,^.* ([0-9]+)$,\1,')"
+year="$(echo $now | sed -e 's,^.* \([0-9][0-9]*\)$,\1,')"
 year_a="$(expr $year - 3)"
 year_b="$(expr $year - 2)"
 date_a="$year_a-01-01"
@@ -16,13 +16,13 @@ touch B -d "$date_b"
 exitcode="$?"
 
 if [ "$exitcode" != 0 ] ; then
-    echo >&2 "*** Wrong exit code:  $exitcode"
-    exit 1
+	echo >&2 "*** Wrong exit code:  $exitcode"
+	exit 1
 fi
 
 if ! fgrep -q "Warning: File target 'A' which has no command is older than its dependency" list.err ; then
-    echo >&2 "*** Warning is missing"
-    exit 1
+	echo >&2 "*** Warning is missing"
+	exit 1
 fi
 
 rm -rf A B
diff --git a/test/past-unchanged/EXEC b/test/past-unchanged/EXEC
--- a/test/past-unchanged/EXEC
+++ b/test/past-unchanged/EXEC
@@ -1,7 +1,7 @@
 #! /bin/sh
 
 now="$(LC_ALL=C date)"
-year="$(echo $now | sed -re 's,^.* ([0-9]+)$,\1,')"
+year="$(echo $now | sed -e 's,^.* \([0-9][0-9]*\)$,\1,')"
 year_past="$(expr $year - 2)"
 date="$year_past-01-01"
 
@@ -16,17 +16,17 @@ ls -l B
 exitcode="$?"
 
 if [ "$exitcode" != 1 ]; then
-    echo >&2 "*** Wrong exit code"
-    exit 1
+	echo >&2 "*** Wrong exit code"
+	exit 1
 fi
 
 if [ "$(fgrep -c "main.stu:11:1: timestamp of file 'B' after execution of its command is older than ../../stu startup" list.err)" != 1 ]; then
-    echo >&2 "*** Missing error message"
+	echo >&2 "*** Missing error message"
 	echo >&2 'actual stderr:'
 	echo >&2 __________________
 	cat >&2 list.err
 	echo >&2 __________________
-    exit 1
+	exit 1
 fi
 
 rm -f A B C
