make all tests work again

diff --git a/test/syntax-error-in-dynamic-k/EXEC b/test/syntax-error-in-dynamic-k/EXEC
--- a/test/syntax-error-in-dynamic-k/EXEC
+++ b/test/syntax-error-in-dynamic-k/EXEC
@@ -21,8 +21,8 @@ if ! fgrep -q "B1:1:4: expected dependency" list.err ; then
     exit 1
 fi
 
-if fgrep -q "*** Targets not remade because of errors" list.err ; then
-    echo >&2 "*** containing '*** Targets not remade because of errors' in error output"
+if fgrep -q "*** Targets not rebuilt because of errors" list.err ; then
+    echo >&2 "*** containing '*** Targets not rebuilt because of errors' in error output"
     exit 1
 fi
 
@@ -45,8 +45,8 @@ if ! fgrep -q "B1:1:4: expected dependency" list.err ; then
     exit 1
 fi
 
-if ! fgrep -q "*** Targets not remade because of errors" list.err ; then
-    echo >&2 "*** not containing '*** Targets not remade because of errors' in error output"
+if ! fgrep -q "*** Targets not rebuilt because of errors" list.err ; then
+    echo >&2 "*** not containing '*** Targets not rebuilt because of errors' in error output"
     exit 1
 fi
 
