be strictly async signal safe in signal handlers

diff --git a/test/fail-j-k/EXEC b/test/fail-j-k/EXEC
--- a/test/fail-j-k/EXEC
+++ b/test/fail-j-k/EXEC
@@ -3,7 +3,7 @@
 doo() { echo "$@" ; "$@" ; }
 
 #
-# No options
+# (1) No options
 #
 
 echo >&2 RUN '(1)'
@@ -12,15 +12,15 @@ doo rm -f ?
 
 echo >&2 ../../stu
 ../../stu 
-exitcode=$?
+exitcode="$?"
 
-if [ $exitcode != 1 ]; then
-    echo >&2 "$: *** Variant without options failed (1)"
-    exit 1
-fi
+[ "$exitcode" = 1 ] || {
+	echo >&2 "$: *** Variant without options failed (1)"
+	exit 1
+}
 
 #
-# With -k 
+# (2) With -k 
 #
 
 echo >&2 RUN '(2)'
@@ -29,30 +29,37 @@ doo rm -f ?
  
 echo >&2 ../../stu -k 
 ../../stu -k &
-PID=$!
+pid="$!"
 
 doo sleep 2
 
 if [ $(ps -fe | grep 74634275 | grep -v grep | wc -l) = 0 ]; then
-    echo >&2 "$0: *** Stu is not running (2)"
-    exit 1
+	echo >&2 "$0: *** Stu is not running (2a)"
+	exit 1
 fi
 
-echo kill -TERM $PID
-kill -TERM $PID  || {
-    echo >&2 "$0: *** Kill (3)"
-    exit 1
+echo "kill -TERM $pid"
+kill -TERM "$pid"  || {
+	echo >&2 "$0: *** Kill (2)"
+	exit 1
 }
 
 doo sleep 1
 
 if [ $(ps -fe | grep 74634275 | grep -v grep | wc -l) != 0 ]; then
-    echo >&2 "$0: *** Stu is still running (4)"
-    exit 1
+	echo >&2 "$0: *** Stu is still running (2b)"
+	ps -fe | grep 74634275 | grep -v grep
+	echo _______________
+	exit 1
 fi
 
+wait "$pid"
+exitcode="$?"
+
+echo "exitcode='$exitcode'"
+
 #
-# With -j2
+# (3) With -j2
 #
 
 echo >&2 RUN '(3)'
@@ -61,15 +68,15 @@ doo rm -f ?
 
 echo >&2 ../../stu -j2
 ../../stu -j2
-exitcode=$?
+exitcode="$?"
 
-if [ $exitcode != 1 ]; then
-    echo >&2 "$: *** Variant without options failed (5)"
-    exit 1
+if [ "$exitcode" != 1 ]; then
+	echo >&2 "$: *** Variant without options failed (3)"
+	exit 1
 fi
 
 #
-# With -j2 -k 
+# (4) With -j2 -k 
 #
 
 echo >&2 RUN '(4)'
@@ -78,22 +85,30 @@ doo rm -f ?
  
 echo >&2 ../../stu -j2 -k 
 ../../stu -j2 -k &
-PID=$!
+pid="$!"
 
 doo sleep 2
 
 if [ $(ps -fe | grep 74634275 | grep -v grep | wc -l) = 0 ]; then
-    echo >&2 "$0: *** Stu is not running (-j2) (6)"
-    exit 1
+	echo >&2 "*** Stu is not running (4a)"
+	exit 1
 fi
 
-doo kill -TERM $PID
+echo "kill -TERM $pid"
+kill -TERM "$pid" || {
+	echo >&2 '*** Kill (4)'
+	exit 1
+}
 
 sleep 1
 
 if [ $(ps -fe | grep 74634275 | grep -v grep | wc -l) != 0 ]; then
-    echo >&2 "$0: *** Stu is still running (-j2) (7)"
-    exit 1
+	echo >&2 "$0: *** Stu is still running (4b)"
+	exit 1
 fi
+
+#
+# End
+#
 
 exit 0
diff --git a/test/remove-incomplete/EXEC b/test/remove-incomplete/EXEC
--- a/test/remove-incomplete/EXEC
+++ b/test/remove-incomplete/EXEC
@@ -17,16 +17,19 @@ echo ../../stu data.A
 exitcode="$?"
 
 if [ "$exitcode" != "1" ]; then
-    echo >&2 "*** Wrong exit code (A)"
+	echo >&2 "*** Wrong exit code (A)"
 	echo >&2 "exitcode=$exitcode"
-    exit 1
+	exit 1
 fi
 
-[ -r list.err ] || exit 1
+[ -r list.err ] || {
+	echo >&2 '*** stderr'
+	exit 1
+}
 
-if fgrep -i "Removing file" list.err ; then
-    echo >&2 "*** wrong error message (A)"
-    exit 1
+if grep -qFi "removing file" list.err ; then 
+	echo >&2 "*** wrong error message (A)"
+	exit 1
 fi
 
 #
@@ -41,16 +44,16 @@ echo ../../stu data.B
 ../../stu 2>list.err data.B
 exitcode="$?"
 
-if [ "$exitcode" != "1" ]; then
-    echo >&2 "*** Wrong exit code (B)"
+[ "$exitcode" = "1" ] || {
+	echo >&2 "*** Wrong exit code (B)"
 	echo >&2 "exitcode=$exitcode"
-    exit 1
-fi
+	exit 1
+}
 
-if ! fgrep "*** Removing file 'list.B' because command failed" list.err ; then
-    echo >&2 "*** missing error message (B)"
-    exit 1
-fi
+grep -qF "*** Removing file 'list.B' because command failed" list.err || {
+	echo >&2 "*** Missing error message (B)"
+	exit 1
+}
 
 #
 # (C) On abort:  File is not removed because it was not changed
@@ -64,19 +67,23 @@ echo ../../stu data.C
 ../../stu 2>list.err data.C &
 pid="$!"
 
-sleep 1
+doo sleep 1
 
+echo "kill -TERM $pid"
 kill -TERM $pid
 
-wait $pid
+wait "$pid"
 exitcode="$?"
 
-[ -r list.err ] || exit 1
+[ -r list.err ] || {
+	echo >&2 '*** stderr'
+	exit 1
+}
 
-if fgrep -i "Removing file" list.err ; then
-    echo >&2 "*** wrong error message (C)"
-    exit 1
-fi
+grep -qFi "removing file" list.err && {
+	echo >&2 "*** Wrong error message (C)"
+	exit 1
+}
 
 #
 # (D) On abort:  File is removed because it was changed
@@ -90,17 +97,18 @@ echo ../../stu data.D
 ../../stu 2>list.err data.D &
 pid="$!"
 
-sleep 1
+doo sleep 1
 
-kill -TERM $pid
+echo "kill -TERM $pid"
+kill -TERM "$pid"
 
-wait $pid
+wait "$pid"
 exitcode="$?"
 
-if ! fgrep "*** Removing file 'list.D' because command failed" list.err ; then
-    echo >&2 "*** missing error message (D)"
-    exit 1
-fi
+grep -qF "*** Removing partially built files" list.err || {
+	echo >&2 "*** Missing error message (D)"
+	exit 1
+}
 
 #
 # End
