update tests

diff --git a/test/chain-transient-command/EXEC b/test/chain-transient-command/EXEC
--- a/test/chain-transient-command/EXEC
+++ b/test/chain-transient-command/EXEC
@@ -1,17 +1,17 @@
 #! /bin/sh
 
-echo ../../stu.test
-../../stu.test >list.out 2>list.err 
-exitcode="$?"
+echo ../../bin/stu.test
+../../bin/stu.test >list.out 2>list.err 
+exitstatus=$?
 
-if [ "$exitcode" != 0 ]; then
-    echo >&2 "$0:  *** stu error"
-    exit 1
+if [ "$exitstatus" != 0 ]; then
+	echo >&2 "$0:  *** stu error"
+	exit 1
 fi
 
-if ! fgrep CORRECT list.out ; then
-    echo >&2 "$0:  *** output does not contain 'CORRECT'"
-    exit 1
+if ! grep -F CORRECT list.out ; then
+	echo >&2 "$0:  *** output does not contain 'CORRECT'"
+	exit 1
 fi
 
 exit 0
diff --git a/test/dangling/EXEC b/test/dangling/EXEC
--- a/test/dangling/EXEC
+++ b/test/dangling/EXEC
@@ -1,16 +1,15 @@
 #! /bin/sh
 
-doo() { echo "$@" ; "$@" ; }
+rm -f ? || exit 2
 
-doo rm -f ?
+ln -s W B || exit 2
 
-doo ln -s W B
+echo ../../bin/stu.test 
+../../bin/stu.test >list.out 2>list.err
+exitstatus=$?
 
-echo ../../stu.test 
-../../stu.test >list.out 2>list.err
-exitcode="$?"
-[ "$exitcode" = 0 ] || {
-	echo >&2 "*** invalid exit code"
+[ "$exitstatus" = 0 ] || {
+	echo >&2 "*** invalid exit status"
 	exit 1
 }
 
@@ -26,6 +25,6 @@ grep -qF 'Executing B' list.out || {
 	exit 1
 }
 
-doo rm -f ?
+rm -f ? || exit 2
 
 exit 0
diff --git a/test/help-newline/EXEC b/test/help-newline/EXEC
--- a/test/help-newline/EXEC
+++ b/test/help-newline/EXEC
@@ -3,10 +3,13 @@
 # The output of 'stu -h' ends in a newline.
 #
 
-../../stu.test -h >list.out
+../../bin/stu.test -h >list.out || {
+	echo >&2 '*** Stu failed'
+	exit 1
+}
 
 # The last byte of the file.  Gets 
-c="$(tail -c 1 list.out)"
+c=$(tail -c 1 list.out)
 
 [ "$c" != '' ] && {
 	echo >&2 '*** stu -h does not end in newline'
diff --git a/test/no-future-persistent/EXEC b/test/no-future-persistent/EXEC
--- a/test/no-future-persistent/EXEC
+++ b/test/no-future-persistent/EXEC
@@ -1,28 +1,28 @@
 #! /bin/sh
 
-rm -f A B || exit 1
+rm -f A B || exit 2
 
 # Create B
 echo $RANDOM >B
-now="$(LC_ALL=C date)"
-year="$(echo $now | sed -e 's,^.* \([0-9][0-9]*\)$,\1,')"
-year_future="$(expr 2 + $year)"
+now=$(LC_ALL=C date)
+year=$(echo $now | sed -e 's,^.* \([0-9][0-9]*\)$,\1,')
+year_future=$(expr 2 + $year)
 date="$year_future"01010700
-touch -t "$date" B
+touch -t "$date" B || exit 2
 
-../../stu.test >list.out 2>list.err
-exitcode="$?"
+../../bin/stu.test >list.out 2>list.err
+exitstatus=$?
 
-if [ "$exitcode" != "0" ]; then
-    echo >&2 "*** wrong exit code"
-    exit 1
+if [ "$exitstatus" != "0" ]; then
+	echo >&2 "*** Exit status incorrect"
+	exit 1
 fi
 
 if cat list.out list.err | grep -i future ; then
-    echo >&2 "*** invalid error message"
-    exit 1
+	echo >&2 "*** Error message incorrect"
+	exit 1
 fi
 
-rm -f A B || exit 1
+rm -f A B || exit 2
 
 exit 0
diff --git a/test/rm-redirect/EXEC b/test/rm-redirect/EXEC
--- a/test/rm-redirect/EXEC
+++ b/test/rm-redirect/EXEC
@@ -1,12 +1,12 @@
 #! /bin/sh
 
-rm -f ?
+rm -f ? || exit 2
 
-../../stu.test >list.out 2>list.err
-exitcode="$?"
+../../bin/stu.test >list.out 2>list.err
+exitstatus="$?"
 
-[ "$exitcode" = 1 ] || {
-	echo >&2 '*** Invalid exit code'
+[ "$exitstatus" = 1 ] || {
+	echo >&2 '*** Invalid exit status'
 	exit 1
 }
 
