make tests faster

diff --git a/test/remove-incomplete/EXEC b/test/remove-incomplete/EXEC
--- a/test/remove-incomplete/EXEC
+++ b/test/remove-incomplete/EXEC
@@ -1,50 +1,46 @@
 #! /bin/sh
 
-doo() { echo >&2 "$@" ; "$@" ; }
-
-rmm() { rm -f ? list.* data.* ; }
+rmm() { rm -f ? list.* data.* || exit 1 ; }
 
 #
 # (A) On error:  File is not removed because it was not changed 
 #
 
-doo rmm
-doo touch list.A
-doo sleep 2
+rmm
+../../sh/touch_old list.A || exit 1
 
-echo ../../stu.test data.A 
 ../../stu.test data.A 2>list.err 
 exitcode="$?"
 
-if [ "$exitcode" != "1" ]; then
+[ "$exitcode" = 1 ] || {
 	echo >&2 "*** Wrong exit code (A)"
 	echo >&2 "exitcode=$exitcode"
 	exit 1
-fi
+}
 
-[ -r list.err ] || {
-	echo >&2 '*** stderr'
+[ -s list.err ] || {
+	echo >&2 '*** Stderr'
 	exit 1
 }
 
-if grep -qFi "removing file" list.err ; then 
-	echo >&2 "*** wrong error message (A)"
+grep -qFi "removing file" list.err 
+exitcode="$?"
+[ "$exitcode" = 1 ] || {
+	echo >&2 "*** Wrong error message (A)"
 	exit 1
-fi
+}
 
 #
 # (B) On error:  File is removed because it was changed
 #
 
-doo rmm
-doo touch list.B
-doo sleep 2
+rmm
+../../sh/touch_old list.B || exit 1
 
-echo ../../stu.test data.B
-../../stu.test 2>list.err data.B
+../../stu.test data.B >list.out 2>list.err 
 exitcode="$?"
 
-[ "$exitcode" = "1" ] || {
+[ "$exitcode" = 1 ] || {
 	echo >&2 "*** Wrong exit code (B)"
 	echo >&2 "exitcode=$exitcode"
 	exit 1
@@ -52,6 +48,15 @@ exitcode="$?"
 
 grep -qF "*** Removing file 'list.B' because command failed" list.err || {
 	echo >&2 "*** Missing error message (B)"
+	echo >&2 stderr:
+	echo >&2 ___________
+	cat >&2 list.err
+	echo >&2 ___________
+	echo >&2 stdout:
+	echo >&2 ___________
+	cat >&2 list.out
+	echo >&2 ___________
+	ls -l 
 	exit 1
 }
 
@@ -59,20 +64,17 @@ grep -qF "*** Removing file 'list.B' because command failed" list.err || {
 # (C) On abort:  File is not removed because it was not changed
 #
 
-doo rmm
-doo touch list.C
-doo sleep 2
+rmm
+../../sh/touch_old list.C || exit 1
 
-echo ../../stu.test data.C
 ../../stu.test 2>list.err data.C &
 pid="$!"
 
-doo sleep 1
+sleep 1 || exit 1
 
-echo "kill -TERM $pid"
-kill -TERM $pid
+kill -TERM $pid || exit 1
 
-wait "$pid"
+wait "$pid" 
 exitcode="$?"
 
 [ -r list.err ] || {
@@ -80,7 +82,8 @@ exitcode="$?"
 	exit 1
 }
 
-grep -qFi "removing file" list.err && {
+grep -qFi "removing file" list.err 
+[ "$?" = 1 ] || {
 	echo >&2 "*** Wrong error message (C)"
 	exit 1
 }
@@ -89,18 +92,15 @@ grep -qFi "removing file" list.err && {
 # (D) On abort:  File is removed because it was changed
 #
 
-doo rmm
-doo touch list.D
-doo sleep 2
+rmm
+../../sh/touch_old list.D || exit 1
 
-echo ../../stu.test data.D
 ../../stu.test 2>list.err data.D &
 pid="$!"
 
-doo sleep 1
+sleep 1 || exit 1
 
-echo "kill -TERM $pid"
-kill -TERM "$pid"
+kill -TERM "$pid" | exit 1
 
 wait "$pid"
 exitcode="$?"
diff --git a/test/symlink/EXEC b/test/symlink/EXEC
--- a/test/symlink/EXEC
+++ b/test/symlink/EXEC
@@ -1,64 +1,37 @@
 #! /bin/sh
 
-doo() { echo "$@" ; "$@" ; }
+set -e
 
-doo rm -f ? list.*
+rm -f ? list.*
 
 # * 'B' is a symlink to an existing file
-doo ln -s W B
+ln -s W B
 echo aaa >W
 
 # * stu is called: 'A' is built
-echo ../../stu.test
+
 ../../stu.test >list.out 2>list.err
-exitcode="$?"
-echo STDOUT:
-cat list.out
-echo ____
-echo STDERR:
-cat list.err
-echo ____
-[ "$exitcode" = 0 ] || {
-	echo >&2 "*** invalid exit code (1)"
-	exit 1
-}
-[ -r A ] || {
-	echo >&2 "*** 'A' does not exist (1)"
-	exit 1
-}
-grep -qF aaa A || {
-	echo >&2 "*** invalid content in 'A' (1)"
-	exit 1
-}
+
+[ -r A ] || { echo >&2 "*** 'A' must exist (1)" ; exit 1 ; }
+grep -qF aaa A || { echo >&2 "*** invalid content in 'A' (1)" ; exit 1 ; }
 
 # * the file pointed to by 'B' is updated
-doo sleep 2
-echo 'echo bbb >W'
+../../sh/touch_old A
+../../sh/touch_old B
 echo bbb >W
 
 # * stu is called: 'A' should be rebuilt 
-echo ../../stu.test
 ../../stu.test >list.out 2>list.err
+
+grep -qF bbb A || { echo >&2 "*** invalid content in 'A' (2)" ; exit 1 ; }
+set +e
+grep -qF 'Nothing to be done' list.out 
 exitcode="$?"
-echo STDOUT:
-cat list.out
-echo ____
-echo STDERR:
-cat list.err
-echo ____
-[ "$exitcode" = 0 ] || {
-	echo >&2 "*** invalid exit code (2)"
-	exit 1
-}
-grep -qF bbb A || {
-	echo >&2 "*** invalid content in 'A' (2)"
-	cat >&2 A
-	echo >&2 ________
-	exit 1
-}
-grep -qF 'Nothing to be done' list.out && {
-	echo >&2 "*** stu should do something (2)"
+[ "$exitcode" = 1 ] || {
+	echo >&2 "*** Stu must do something (2)"
 	exit 1
 }
 
-doo rm -f ? list.*
+rm -f ? list.* || exit 1
+
+exit 0
